### ISSUE TITLE
Bundle exercism CLI for testing?

### ISSUE THREAD

**Issue by canweriotnow** [canweriotnow/exercism-emacs#11]
Although my long-term goal is to remove dependency on the CLI, I'm wondering if it wouldn't be expedient to bundle it in the Travis config for CI builds, as wrapping the CLI seems to be the state of affairs for the foreseeable future. Although, it surely would be bad form to actually hit the exercism API every time the test suite is run.

Open to ideas about this.

**Comment by verdammelt** [comment]
Can you make sure that exercism CLI run in the tests run against a "fake" config? You could create a test user on exercism.io for the tests to use.

**Comment by canweriotnow** [comment]
@verdammelt That's exactly what I was thinking... it would be easy enough to create a test user and submit/unsubmit/fetch on its behalf... I just didn't want to inadvertently cause annoyance for @kytrinyx et al. in doing so.

**Comment by wobh** [comment]
Test user could get a bunch of code reviews and nitpicks from people who don't know it's a dog. That seems unfair to them. You'd want to mock it anyway. The functions for using exercism API actions will need the same protective assertions and the same asynchronicity regardless if they're using the CLI or not.

**Comment by wobh** [comment]
Or you could stand up your own exercism-api for test purposes and configure the tests to use that.https://github.com/exercism/x-api. Probably have to hack into it's own test settings to use it in test mode... Forget it. Just mock.

**Comment by kytrinyx** [comment]
I wouldn't bundle the CLI binary, simply because it's too big. It shouldn't be too hard to grab the latest release, though. I wrote a simple bash script that does that for a different binary, and travis runs the bash script first, then a command. https://github.com/exercism/xruby/blob/master/bin/fetch-configlet

It's straight-forward to configure the CLI to use alternate endpoints. You can fetch from x.exercism.io all you want without affecting anyone on the site, but @wobh makes a good point about code/nitpicks for a test user showing up on exercism.io would potentially cause people to sink time into nitpicking it, which would be a shame. I'm not sure if there's an easy way to get a test site running. x-api is straight forward, but the exercism.io setup is pretty haphazard.

**Comment by canweriotnow** [comment]
@kytrinyx I was more thinking of having Travis install it in the before_test setup, but @wobh is right about having a test user cluttering up the main site, and I don't like the idea of remote dependencies for testing. My latest thought (while wrapping the CLI) is to have the CI setup put a bash script in the $PATH so things like `which exercism` work, and just stub out the expected responses from the CLI until such time as it's no longer a dependency.

**Comment by kytrinyx** [comment]
Yeah, having remote testing dependencies feels brittle (and a bit dirty, but sometimes a bit of dirt is what it takes). If the bash script to mock it out works, then that seems like a reasonable approach.

**Comment by canweriotnow** [comment]
I'm going to close this as it looks like the consensus is using the actual CLI for testing is a bad idea. FWIW, I've started a new branch, [no-cli](https://github.com/canweriotnow/exercism-emacs/tree/no-cli) for playing with direct API calls w/o the CLI. So it might be a moot point if that goes quickly, otherwise I'll whip up a bash script for emulating the CLI in testing.
