### ISSUE TITLE
Setup unit tests with ERT

### ISSUE THREAD

**Issue by wobh** [canweriotnow/exercism-emacs#8]

**Comment by canweriotnow** [comment]
What do you think about using something like [el-expectations.el](http://www.emacswiki.org/emacs/EmacsLispExpectations), since it supports mocks/stubs with [el-mock.el](http://www.emacswiki.org/emacs/EmacsLispMock)? 

Since we're dealing with http responses, being able to mock/stub might come in handy.

**Comment by canweriotnow** [comment]
Added Cask, ert, ert-expectations

**Comment by wobh** [comment]
No opinion. I usually mock with flet.

**Comment by canweriotnow** [comment]
@wobh Currently just using regular ERT... realized mocking is going to be difficult wrapping the CLI, discussion in #11
